#!/usr/bin/env sh
set -eu

REPO="${CHEZMOI_REPO:-BinaryMisfit/dotfiles}"

LOCAL_BIN="$HOME/.local/bin"

CHEZMOI_DIR="$HOME/.config/chezmoi"
CHEZMOI_CONFIG="$CHEZMOI_DIR/chezmoi.yaml"

AGE_DIR="$HOME/.config/age"
AGE_KEY="$AGE_DIR/key.txt"

SOURCE_DIR="$HOME/.local/share/chezmoi"
SSH_REMOTE="git@github.com:${REPO}.git"

SSH_DIR="$HOME/.ssh"
SSH_KEY="$SSH_DIR/id_ed25519_github"

export PATH="$LOCAL_BIN:$PATH"

section() { printf '\n==> %s\n' "$1"; }
info() { printf '  %s\n' "$1"; }
die() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

section "bootstrap"
info "repo: $REPO"

# --------------------------------------------------
# base deps
# --------------------------------------------------
if ! command -v git >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
  section "base deps"
  info "installing git/curl"
  if command -v apt-get >/dev/null 2>&1; then
    sudo apt-get update -y
    sudo apt-get install -y git curl ca-certificates
  elif command -v brew >/dev/null 2>&1; then
    brew install git curl
  else
    die "no supported package manager found for git/curl (expected apt-get or brew)"
  fi
fi

# --------------------------------------------------
# core tools (chezmoi, age)
# --------------------------------------------------
section "core tools"

mkdir -p "$LOCAL_BIN"

if ! command -v chezmoi >/dev/null 2>&1 && [ ! -x "$LOCAL_BIN/chezmoi" ]; then
  info "installing chezmoi"
  sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$LOCAL_BIN"
else
  info "chezmoi already installed"
fi

if ! command -v age-keygen >/dev/null 2>&1; then
  info "installing age"
  if command -v brew >/dev/null 2>&1; then
    brew install age
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install -y age
  else
    die "no supported package manager found for age (expected brew or apt-get)"
  fi
else
  info "age already installed"
fi

export PATH="$LOCAL_BIN:$PATH"

CHEZMOI="$(command -v chezmoi || true)"
[ -n "$CHEZMOI" ] || CHEZMOI="$LOCAL_BIN/chezmoi"
AGE_KEYGEN="$(command -v age-keygen || true)"
SSH_KEYGEN="$(command -v ssh-keygen || true)"

[ -x "$CHEZMOI" ] || die "chezmoi not found after install"
[ -n "$AGE_KEYGEN" ] || die "age-keygen not found after install"
[ -n "$SSH_KEYGEN" ] || die "ssh-keygen not found"

info "chezmoi: $CHEZMOI"
info "age-keygen: $AGE_KEYGEN"

# --------------------------------------------------
# age identity
# --------------------------------------------------
section "age identity"

mkdir -p "$CHEZMOI_DIR" "$AGE_DIR"

if [ ! -f "$AGE_KEY" ]; then
  info "generating machine-local age key"
  "$AGE_KEYGEN" -o "$AGE_KEY"
  chmod 600 "$AGE_KEY"
else
  info "key already exists: $AGE_KEY"
fi

AGE_RECIPIENT="$(sed -n 's/^# public key: //p' "$AGE_KEY" | head -n 1)"
[ -n "$AGE_RECIPIENT" ] || die "failed to read age public key"

# Consumed by .chezmoi.yaml.tmpl's `env "CHEZMOI_AGE_RECIPIENT"` - the config
# file itself is generated by `chezmoi init` below, not hand-written here.
export CHEZMOI_AGE_RECIPIENT="$AGE_RECIPIENT"

# --------------------------------------------------
# github ssh key
# --------------------------------------------------
section "github ssh key"

mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"

if [ ! -f "$SSH_KEY" ]; then
  info "generating machine-local GitHub SSH key"
  "$SSH_KEYGEN" -t ed25519 -C "github-dotfiles-$(hostname)" -f "$SSH_KEY" -N ""
  chmod 600 "$SSH_KEY"
  chmod 644 "$SSH_KEY.pub"
else
  info "key already exists: $SSH_KEY"
fi

SSH_PUBLIC_KEY="$(cat "$SSH_KEY.pub")"

# --------------------------------------------------
# chezmoi source
# --------------------------------------------------
section "chezmoi source"

if [ ! -d "$SOURCE_DIR" ]; then
  info "initializing source: $REPO"
  info "you'll be prompted for this machine's profile (work/home) and git identity"
  "$CHEZMOI" init "$REPO"
else
  info "source already exists: $SOURCE_DIR"
fi

# --------------------------------------------------
# git remote
# --------------------------------------------------
section "git remote"

if [ -d "$SOURCE_DIR/.git" ]; then
  CURRENT_REMOTE="$(git -C "$SOURCE_DIR" remote get-url origin 2>/dev/null || true)"

  if [ "$CURRENT_REMOTE" != "$SSH_REMOTE" ]; then
    info "setting origin to SSH: $SSH_REMOTE"
    git -C "$SOURCE_DIR" remote set-url origin "$SSH_REMOTE"
  else
    info "origin already uses SSH"
  fi
else
  info "chezmoi source is not a git repo, skipping remote update"
fi

# --------------------------------------------------
# next steps
# --------------------------------------------------
section "next steps"

CHEZ='chezmoi update && chezmoi diff && chezmoi apply'

printf '\nAge Public Key:\n  %s\n\n' "$AGE_RECIPIENT"
printf 'GitHub SSH Key:\n  %s\n\n' "$SSH_PUBLIC_KEY"

printf 'If this repo has encrypted files by the time you read this: add the age\n'
printf 'public key above to the recipients list in chezmoi config on an existing\n'
printf 'trusted machine, re-encrypt each affected file with '"'"'chezmoi encrypt'"'"', then\n'
printf 'commit and push from there. Nothing in this repo is encrypted as of writing\n'
printf '(see ADR 0002) - this step has no concrete command until that changes.\n\n'

printf 'When done run:\n  %s\n\n' "$CHEZ"
printf 'Verify:\n'
printf '  ssh -T git@github.com\n'
printf '  git -C "%s" remote -v\n' "$SOURCE_DIR"
printf '  grep -A1 "^update:" "%s"\n\n' "$CHEZMOI_CONFIG"

printf 'bootstrap: complete\n'
