#!powershell
$ErrorActionPreference = "Stop"

$Repo = $env:CHEZMOI_REPO
if (-not $Repo) {
    $Repo = "BinaryMisfit/dotfiles"
}

$ChezmoiDir = "$HOME\.config\chezmoi"
$ChezmoiConfig = "$ChezmoiDir\chezmoi.yaml"

$AgeDir = "$HOME\.config\age"
$AgeKey = "$AgeDir\key.txt"

$SourceDir = "$HOME\.local\share\chezmoi"
$SshRemote = "git@github.com:$Repo.git"

$SshDir = "$HOME\.ssh"
$SshKey = "$SshDir\id_ed25519_github"

function Section {
    param([string]$Name)
    Write-Host ""
    Write-Host "==> $Name"
}

function Info {
    param([string]$Message)
    Write-Host "  $Message"
}

function Die {
    param([string]$Message)
    throw "ERROR: $Message"
}

Section "bootstrap"
Info "repo: $Repo"

Section "core tools"

$WingetPackages = @("Git.Git", "twpayne.chezmoi", "FiloSottile.age", "GnuPG.Gpg4win")

foreach ($Package in $WingetPackages) {
    Info "ensuring $Package"
    winget install --id $Package --exact --silent --accept-package-agreements --accept-source-agreements
}

if (-not (Get-Command ssh-keygen -ErrorAction SilentlyContinue)) {
    Info "installing OpenSSH client capability"
    Add-WindowsCapability -Online -Name "OpenSSH.Client~~~~0.0.1.0" | Out-Null
} else {
    Info "OpenSSH client already installed"
}

# Refresh PATH in this process: winget-installed tools land on the machine/user
# PATH via registry but this session's environment doesn't see them yet.
$env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")

$Chezmoi = Get-Command chezmoi -ErrorAction SilentlyContinue
$AgeKeygen = Get-Command age-keygen -ErrorAction SilentlyContinue
$SshKeygen = Get-Command ssh-keygen -ErrorAction SilentlyContinue

if (-not $Chezmoi) { Die "chezmoi not found after install" }
if (-not $AgeKeygen) { Die "age-keygen not found after install" }
if (-not $SshKeygen) { Die "ssh-keygen not found after install" }

Info "chezmoi: $($Chezmoi.Source)"
Info "age-keygen: $($AgeKeygen.Source)"

Section "age identity"

New-Item -ItemType Directory -Force -Path $ChezmoiDir | Out-Null
New-Item -ItemType Directory -Force -Path $AgeDir | Out-Null

if (-not (Test-Path $AgeKey)) {
    Info "generating machine-local age key"
    age-keygen -o $AgeKey | Out-Null
} else {
    Info "key already exists: $AgeKey"
}

$AgeRecipient = Select-String "# public key:" $AgeKey |
    ForEach-Object { $_.Line -replace "# public key: ", "" } |
    Select-Object -First 1

if (-not $AgeRecipient) {
    Die "failed to read age public key"
}

# Consumed by .chezmoi.yaml.tmpl's `env "CHEZMOI_AGE_RECIPIENT"` — the config
# file itself is generated by `chezmoi init` below, not hand-written here.
$env:CHEZMOI_AGE_RECIPIENT = $AgeRecipient

Section "github ssh key"

New-Item -ItemType Directory -Force -Path $SshDir | Out-Null

if (-not (Test-Path $SshKey)) {
    Info "generating machine-local GitHub SSH key"
    ssh-keygen -t ed25519 -C "github-dotfiles-$env:COMPUTERNAME" -f $SshKey -N "" | Out-Null
} else {
    Info "key already exists: $SshKey"
}

$SshPublicKey = Get-Content "$SshKey.pub" -ErrorAction SilentlyContinue
if (-not $SshPublicKey) {
    Die "failed to read SSH public key"
}

Section "chezmoi source"

if (-not (Test-Path $SourceDir)) {
    Info "initializing source: $Repo"
    Info "you'll be prompted for this machine's profile (work/home) and git identity"
    chezmoi init $Repo
} else {
    Info "source already exists: $SourceDir"
}

Section "git remote"

if (Test-Path "$SourceDir\.git") {
    $CurrentRemote = git -C $SourceDir remote get-url origin 2>$null

    if ($CurrentRemote -ne $SshRemote) {
        Info "setting origin to SSH: $SshRemote"
        git -C $SourceDir remote set-url origin $SshRemote
    } else {
        Info "origin already uses SSH"
    }
} else {
    Info "chezmoi source is not a git repo, skipping remote update"
}

Section "next steps"

$ChezmoiNext = 'chezmoi update; chezmoi diff; chezmoi apply'

Write-Host ""
Write-Host "Age Public Key:"
Write-Host "  $AgeRecipient"
Write-Host ""

Write-Host "GitHub SSH Key:"
Write-Host "  $SshPublicKey"
Write-Host ""

Write-Host "If this repo has encrypted files by the time you read this: add the age"
Write-Host "public key above to the recipients list in chezmoi config on an existing"
Write-Host "trusted machine, re-encrypt each affected file with 'chezmoi encrypt', then"
Write-Host "commit and push from there. Nothing in this repo is encrypted as of writing"
Write-Host "(see ADR 0002) - this step has no concrete command until that changes."
Write-Host ""

Write-Host "When done run:"
Write-Host "  $ChezmoiNext"
Write-Host ""

Write-Host "Verify:"
Write-Host "  ssh -T git@github.com"
Write-Host "  git -C `"$SourceDir`" remote -v"
Write-Host "  chezmoi data"
Write-Host "  Select-String -Path `"$ChezmoiConfig`" -Pattern `"^update:`",`"^\s+apply:`""
Write-Host ""

Write-Host "bootstrap: complete"
