[tools]
age = "latest"
bat = "latest"
chezmoi = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
lazygit = "latest"
neovim = "stable"
node = "lts"
python = "3.14"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
stylua = "latest"
tree-sitter = "latest"
yq = "latest"
